name: Re-enable workflows

on:
  workflow_dispatch:

jobs:
  enable-wf:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Workflows
        # Replace main by the release of your choice
        uses: fgerthoffert/actions-workflow-keepalive@main
        with:
          org: zencrepes
          token: ${{ secrets.API_KEY }}
